-- One-shot: add the export snapshot cutoff (snapshot_mjd) to an existing
-- users SQLite file whose export_task table predates the column. Only needed
-- when the database must be preserved (it holds real accounts); otherwise
-- recreate it from tools/usersdb_schema.sql, which already includes the
-- column.
--
-- The DEFAULT sentinel (1e9, far above any real alert MJD) means "no cutoff"
-- for historical rows: old exports are terminal (SUCCESS/FAILED) and never
-- re-executed, and the app renders only real cutoffs as dates (export.py
-- hides values >= 1e8 instead of converting the sentinel to a datetime,
-- which would fail — MJD 1e9 is beyond datetime's year range). Note:
-- databases altered by this script carry a DDL DEFAULT that fresh databases
-- created from usersdb_schema.sql lack. Harmless — the application always
-- supplies the value on insert.
--
-- The application never alters the database itself. Do not re-run: SQLite
-- ADD COLUMN fails on an existing column.
--
--   sqlite3 /path/to/users.db < tools/apply_export_snapshot_mjd.sql

ALTER TABLE export_task ADD COLUMN snapshot_mjd REAL NOT NULL DEFAULT 1e9;
